### ISSUE TITLE
Login to Hangouts/Google chat

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/hamsket#290]
Steps to reproduce

  Insert new hangouts chat and log in.

Expected behavior

  Continue to insert password after entering email.

Actual behavior

Error message:
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in

At first I have this error only with czech language selected on the login page. Now it does not matter.

ENVIRONMENT

    Hamsket: v0.6.3

    OS: Windows 10 Pro

    Arch: x64

    BuildVersion: 4b36e9f

    Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
In theory, it should be fixed on 0c6cda40.

**Comment by LiBOSS-CZ** [comment]
No, it is not fixed:-(.

**Comment by reggermont** [comment]
Confirmed, update did not fixed the issue. Also tried with a latest Chrome user agent and still not working

![image](https://user-images.githubusercontent.com/14902909/145857539-95b9ed3b-bb5c-4839-8401-3ef31325ef99.png)

**Comment by reggermont** [comment]
Works for me today, may be a bug on Google side

**Comment by reggermont** [comment]
Found out issue may comes from User Agent. Can connect with this one:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
```

**Comment by timkgh** [comment]
Same issue in Rambox CE 0.7.9 but that uses older Chromium and Node:
https://github.com/ramboxapp/community-edition/issues/3187

**Comment by Foggalong** [comment]
Yeah I'm still getting this issue, even with latest nightly and @reggermont's suggested user agent :cry:

**Comment by reureya** [comment]
I think it probably has to do with Google's attempts to block MitM attacks from embedded browser frameworks.

[Explanatory blog post from Google](https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html)

Google's "[Guidance to developers affected by our effort to block less secure browsers and applications](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)"

**Comment by reureya** [comment]
Follow up: I got it to work now.

I first tried just reloading the tab a few times and then restarting Hamsket, which didn't help. Then the cache clear and reboot, after which I entered the full email address (including @gmail.com, which I don't think I did before).

Not sure what precisely the magic step was, but probably clearing the cache, restarting Hamsket, and entering the full address taken together is a tip worth trying.
